// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFyxZQB4RwWEc_Oud9L0Ob3n5GusOt6A',
    appId: '1:828918326978:web:a5ff968436566788373d5b',
    messagingSenderId: '828918326978',
    projectId: 'aqua-commerce-f454b',
    authDomain: 'aqua-commerce-f454b.firebaseapp.com',
    storageBucket: 'aqua-commerce-f454b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACI83v2zYSekLtJVPxs4hu5siJAqDBrbM',
    appId: '1:828918326978:android:24dd06044383f53b373d5b',
    messagingSenderId: '828918326978',
    projectId: 'aqua-commerce-f454b',
    storageBucket: 'aqua-commerce-f454b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVtHUkxR_IbTwG4gOIz7wq7Ec5tHj_4Gc',
    appId: '1:828918326978:ios:ff30a524d243a78c373d5b',
    messagingSenderId: '828918326978',
    projectId: 'aqua-commerce-f454b',
    storageBucket: 'aqua-commerce-f454b.firebasestorage.app',
    iosBundleId: 'com.example.farmCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVtHUkxR_IbTwG4gOIz7wq7Ec5tHj_4Gc',
    appId: '1:828918326978:ios:ff30a524d243a78c373d5b',
    messagingSenderId: '828918326978',
    projectId: 'aqua-commerce-f454b',
    storageBucket: 'aqua-commerce-f454b.firebasestorage.app',
    iosBundleId: 'com.example.farmCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdFyxZQB4RwWEc_Oud9L0Ob3n5GusOt6A',
    appId: '1:828918326978:web:62de1d0272c9e4fb373d5b',
    messagingSenderId: '828918326978',
    projectId: 'aqua-commerce-f454b',
    authDomain: 'aqua-commerce-f454b.firebaseapp.com',
    storageBucket: 'aqua-commerce-f454b.firebasestorage.app',
  );

}